"""Backtest engine with full equity curve, drawdown tracking, and per-trade P&L."""

import pandas as pd
import numpy as np
from .metrics import compute_all


class BacktestEngine:
    """Simulates trading based on signals generated by a strategy."""

    def __init__(self, initial_capital: float = 10000.0, fee_pct: float = 0.006):
        self.initial_capital = initial_capital
        self.fee_pct = fee_pct

    def run(self, df: pd.DataFrame, stop_loss_pct: float = 0.0) -> dict:
        """Run backtest and return full metrics.

        Args:
            df: DataFrame with 'close' and 'signal' columns (1=BUY, -1=SELL, 0=HOLD).
            stop_loss_pct: If > 0, auto-sell when position drops by this fraction.

        Returns:
            Dict with all performance metrics.
        """
        capital = self.initial_capital
        position = 0.0
        entry_price = 0.0
        trade_pnls: list[float] = []
        equity_values: list[float] = [self.initial_capital]
        trade_log: list[dict] = []

        for i in range(1, len(df)):
            row = df.iloc[i]
            prev_row = df.iloc[i - 1]
            price = row["close"]
            signal = prev_row.get("signal", 0)

            # Stop loss check
            if stop_loss_pct > 0 and position > 0 and entry_price > 0:
                loss_pct = (price - entry_price) / entry_price
                if loss_pct <= -stop_loss_pct:
                    signal = -1  # Force sell

            # BUY
            if signal == 1 and position == 0:
                fee = capital * self.fee_pct
                position = (capital - fee) / price
                entry_price = price
                capital = 0.0
                trade_log.append({
                    "type": "BUY",
                    "price": round(price, 2),
                    "size": round(position, 6),
                    "fee": round(fee, 2),
                    "bar": i,
                })

            # SELL
            elif signal == -1 and position > 0:
                gross = position * price
                fee = gross * self.fee_pct
                capital = gross - fee
                pnl = capital - (position * entry_price)
                trade_pnls.append(pnl)
                trade_log.append({
                    "type": "SELL",
                    "price": round(price, 2),
                    "size": round(position, 6),
                    "fee": round(fee, 2),
                    "pnl": round(pnl, 2),
                    "bar": i,
                })
                position = 0.0
                entry_price = 0.0

            # Track equity (mark-to-market)
            equity = capital + (position * price)
            equity_values.append(equity)

        equity_curve = pd.Series(equity_values)

        # Compute all metrics
        results = compute_all(equity_curve, trade_pnls)
        results["initial_capital"] = self.initial_capital
        results["fee_pct"] = self.fee_pct
        results["stop_loss_pct"] = stop_loss_pct
        results["trade_log"] = trade_log[-20:]  # Last 20 trades for context

        return results
