import pandas as pd
import json


class BacktestEngine:
    """Simulates trading based on signals generated by a strategy."""

    def __init__(self, initial_capital=10000.0, fee_pct=0.005):
        self.initial_capital = initial_capital
        self.fee_pct = fee_pct

    def run(self, df: pd.DataFrame) -> dict:
        """Runs the backtest and returns metrics."""
        capital = self.initial_capital
        position = 0
        trades = 0

        for i in range(1, len(df)):
            row = df.iloc[i]
            prev_row = df.iloc[i - 1]

            signal = prev_row.get("signal", 0)
            price = row["close"]

            # BUY
            if signal == 1 and position == 0:
                position = (capital * (1 - self.fee_pct)) / price
                capital = 0
                trades += 1

            # SELL
            elif signal == -1 and position > 0:
                capital = (position * price) * (1 - self.fee_pct)
                position = 0
                trades += 1

        # Mark to market at the end
        final_value = capital
        if position > 0:
            final_value += position * df.iloc[-1]["close"]

        roi = (final_value - self.initial_capital) / self.initial_capital

        return {
            "initial_capital": self.initial_capital,
            "final_value": final_value,
            "roi_pct": round(roi * 100, 2),
            "trades_executed": trades,
            # Sharpe ratio placeholder (would need daily returns for real calc)
            "sharpe_ratio_estimated": round(roi / 0.15, 2) if roi > 0 else 0.0,
        }
